services:
  dev_place:
    image: debian:12.5
    entrypoint:
      - "bash"
    command: [
      '-c',
      'yes > /dev/null 2>&1'
    ]
    depends_on:
      - proxy
  proxy:
    image: envoyproxy/envoy:contrib-v1.29.3
    environment:
      GODEBUG: cgocheck=0
    command:
      - "-c /envoy-demo.yaml"
    volumes:
      - ./envoy-demo.yaml:/envoy-demo.yaml
      - ./_out/lib.so:/lib/lib.so
    depends_on:
    - echo_service
    ports:
    - "${PORT_PROXY:-10000}:10000"

  echo_service:
    image: kong/go-echo:latest
    hostname: echo_service
