services:
  proxy:
    image: envoyproxy/envoy:contrib-v1.29.2
    command:
      - "-c /envoy-demo.yaml"
    volumes:
      - ./envoy-demo.yaml:/envoy-demo.yaml
      - ./_out/lib.so:/lib/lib.so
    depends_on:
    - echo_service
    ports:
    - "${PORT_PROXY:-10000}:10000"

  echo_service:
    image: kong/go-echo:latest
    hostname: echo_service
